import Head from 'next/head'
import { Inter } from '@next/font/google'
import SignUp from '../components/SignUp';
import Login from '../components/Login';
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Employee Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mt-4 lg:mx-16 md:mx-6'>
        
        <div>
          <h1 className='flex justify-center text-5xl text-white'>User Authentication</h1>
        <div className='flex min-h-screen mt-12 justify-evenly'>
        <SignUp></SignUp>
        <Login></Login>
        </div>
        </div>

      </main>
    </>
  )
}
