import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useState } from 'react'
import Table from '../components/Table';
import Form from '../components/Form';
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const [isDataChanged, setIsDataChanged] = useState(false);
  const [isFormActive, setIsFormActive] = useState(false);
  const [gotData, setGotData] = useState({});
  const [isEditButtonPressed, setIsEditButtonPressed] = useState(false); 
  const [pressedUserId, setPressedUserId] = useState(''); 
  console.log(pressedUserId); 
  return (
    <>
      <Head>
        <title>Employee Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mt-4 lg:mx-16 md:mx-6'>
        <div>
          <Form isDataChanged={isDataChanged} setIsDataChanged={setIsDataChanged} isFormActive={isFormActive} setIsFormActive={setIsFormActive} setGotData={setGotData} isEditButtonPressed={isEditButtonPressed} setIsEditButtonPressed={setIsEditButtonPressed} pressedUserId={pressedUserId}></Form>
        </div>
        <div className='flex justify-center mb-8'>
          <Table setIsDataChanged={setIsDataChanged} setIsFormActive={setIsFormActive} gotData={gotData} setIsEditButtonPressed={setIsEditButtonPressed} setPressedUserId={setPressedUserId}></Table>
        </div>
      </main>
    </>
  )
}
